#!/bin/bash

dot-checkout

if [[ -e ~/.config/profile ]]; then
	source ~/.config/profile
else
	echo -n "Which editor do you prefer? (e.g. nano, vim, emacs): "
	read EDITOR
	[[ -z "$EDITOR" ]] && EDITOR='vim'
	export EDITOR
	[[ "$EDITOR" == 'vim' ]] && VISUAL='vim'
	cat <<-EOF > ~/.config/profile
	export EDITOR='$EDITOR'
	export VISUAL='$VISUAL'
	EOF
fi

if ! git config user.email > /dev/null; then
	echo "Git configuration"
	echo -n "What's your name? (e.g. John Doe): "
	read NAME
	git config --file ~/.gitconfig user.name "$NAME"
	echo -n "What's your email? (e.g. john@doe.com): "
	read EMAIL
	git config --file ~/.gitconfig user.email "$EMAIL"
fi

if command -v xfconf-load > /dev/null; then
	echo -n "Do you want to load the Xfce configuration? (y/N): "
	read load
	[[ "$load" == 'y' ]] && xfconf-load ~/.config/xfconf-helper/config.yml
fi

mkdir -p ~/{download,documents/{,pictures}}
mkdir -p ~/.local/share/histstat
chmod go-rw ~/.config/msmtp/config

git clone https://github.com/felipec/vim-felipec.git ~/.vim/pack/colors/start/felipec 2> /dev/null
git clone https://github.com/itchyny/lightline.vim.git ~/.vim/pack/plugins/start/lightline 2> /dev/null
git clone https://github.com/dense-analysis/ale.git ~/.vim/pack/plugins/start/ale 2> /dev/null
git clone https://github.com/tpope/vim-commentary ~/.vim/pack/plugins/start/commentary 2> /dev/null

# Create GTK bookmarks
if [[ ! -e ~/.config/gtk-3.0/bookmarks ]]; then
	mkdir -p ~/.config/gtk-3.0 &&
	cat <<-EOF > ~/.config/gtk-3.0/bookmarks
	file:///home/$USER/documents
	file:///home/$USER/download
	file:///home/$USER/tmp
	EOF
fi
