#!/bin/bash

dot-checkout

mkdir -p ~/{downloads,documents/{,pictures}}
mkdir -p ~/.local/share/histstat
chmod go-rw ~/.msmtprc

git clone https://github.com/felipec/vim-felipec.git ~/.vim/pack/colors/start/felipec
git clone https://github.com/itchyny/lightline.vim.git ~/.vim/pack/plugins/start/lightline
git clone https://github.com/vim-syntastic/syntastic.git ~/.vim/pack/plugins/start/syntastic
git clone https://github.com/tpope/vim-commentary ~/.vim/pack/plugins/start/commentary

if command -v xfconf-load > /dev/null; then
	echo -n "Do you want to load the Xfce configuration? (y/N): "
	read load
	[[ "$load" == 'y' ]] && xfconf-load ~/.config/xfconf-helper/config.yml
fi

cat <<EOF > ~/.config/gtk-3.0/bookmarks
file:///home/$USER/documents
file:///home/$USER/downloads
EOF
