#!/bin/bash

dot-checkout

source ~/.config/profile

if command -v xfconf-load > /dev/null; then
	xfconf-load ~/.config/xfconf-helper/config.yml
fi

mkdir -p ~/{download,documents/{,pictures}}
mkdir -p ~/.local/share/histstat
chmod go-rw ~/.config/msmtp/config

git clone https://github.com/felipec/vim-felipec.git ~/.vim/pack/colors/start/felipec 2> /dev/null
git clone https://github.com/itchyny/lightline.vim.git ~/.vim/pack/plugins/start/lightline 2> /dev/null
git clone https://github.com/dense-analysis/ale.git ~/.vim/pack/plugins/start/ale 2> /dev/null
git clone https://github.com/tpope/vim-commentary ~/.vim/pack/plugins/start/commentary 2> /dev/null

# Create GTK bookmarks
if [[ ! -e ~/.config/gtk-3.0/bookmarks ]]; then
	mkdir -p ~/.config/gtk-3.0 &&
	cat <<-EOF > ~/.config/gtk-3.0/bookmarks
	file:///home/$USER/documents
	file:///home/$USER/download
	file:///run/media/$USER/backup/
	file:///home/$USER/tmp
	EOF
fi
