---
shortcuts:
  commands:
    "<Super>Return": xfce4-terminal
    "<Super>b": browser
    "<Super>l": xfce4-screensaver-command --lock
    "<Super>r": rlaunch
    "<Super>r/startup-notify": false
    "<Super>w": xfce4-popup-whiskermenu
    "<Super>space": xfce4-terminal --drop-down --hide-menubar
    "<Super>v": record
  wm:
    left_workspace: "<Super>Left"
    right_workspace: "<Super>Right"
    up_workspace: "<Super>Up"
    down_workspace: "<Super>Down"
    workspace_1: "<Super>1"
    workspace_2: "<Super>2"
    workspace_3: "<Super>3"
    workspace_4: "<Super>4"
    workspace_5: "<Super>5"
    workspace_6: "<Super>6"
    workspace_7: "<Super>7"
    workspace_8: "<Super>8"
    show_desktop: "<Super>d"
    move_window_left_workspace: "<Primary><Super>Left"
    move_window_right_workspace: "<Primary><Super>Right"
    move_window_up_workspace: "<Primary><Super>Up"
    move_window_down_workspace: "<Primary><Super>Down"
    move_window_workspace_1: "<Primary><Super>1"
    move_window_workspace_2: "<Primary><Super>2"
    move_window_workspace_3: "<Primary><Super>3"
    move_window_workspace_4: "<Primary><Super>4"
    move_window_workspace_5: "<Primary><Super>5"
    move_window_workspace_6: "<Primary><Super>6"
    move_window_workspace_7: "<Primary><Super>7"
    move_window_workspace_8: "<Primary><Super>8"
settings:
  xfwm4:
    "/general/easy_click": Super
    "/general/cycle_tabwin_mode": 0
    "/general/cycle_preview": false
    "/general/workspace_count": 8
    "/general/theme": Arc-Darker
    "/general/titleless_maximize": true
    "/general/scroll_workspaces": false
    "/general/show_dock_shadow": false
    "/general/show_frame_shadow": false
    "/general/move_opacity": 50
    "/general/popup_opacity": 90
    "/general/resize_opacity": 75
    "/general/snap_width": 25
    "/general/placement_ratio": 60
    "/general/title_font": Sans Bold 10
    "/general/cycle_hidden": false
    "/general/workspace_names":
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
  xfce4-session:
    "/general/SaveOnExit": false
    "/compat/LaunchGNOME": true
    "/general/LockCommand": xfce4-screensaver-command --lock
  xfce4-desktop:
    "/desktop-icons/style": 0
    "/backdrop/screen0/monitoreDP/workspace0/last-image": "/usr/share/backgrounds/archlinux/simple.png"
  xfce4-panel:
    "/panels/dark-mode": true
  keyboards:
    "/Default/KeyRepeat/Delay": 200
    "/Default/KeyRepeat/Rate": 50
  xsettings:
    "/Net/ThemeName": Arc-Darker
    "/Net/IconThemeName": Arc-X-D
    "/Xft/DPI": 108
    "/Gtk/CursorThemeName": Vanilla-DMZ
    "/Net/CursorBlinkTime": 500
    "/Xft/HintStyle": hintnone
    "/Xft/Hinting": 0
    "/Xft/RGBA": rgb
  xfce4-power-manager:
    "/xfce4-power-manager/show-panel-label": 0
    "/xfce4-power-manager/sleep-button-action": !uint 1
    "/xfce4-power-manager/power-button-action": !uint 4
    "/xfce4-power-manager/battery-button-action": !uint 3
    "/xfce4-power-manager/hibernate-button-action": !uint 1
    "/xfce4-power-manager/inactivity-on-ac": !uint 15
    "/xfce4-power-manager/inactivity-on-battery": !uint 15
    "/xfce4-power-manager/inactivity-sleep-mode-on-battery": !uint 1
    "/xfce4-power-manager/lid-action-on-ac": !uint 1
    "/xfce4-power-manager/lid-action-on-battery": !uint 1
    "/xfce4-power-manager/dpms-enabled": false
    "/xfce4-power-manager/general-notification": false
    "/xfce4-power-manager/logind-handle-hibernate-key": false
    "/xfce4-power-manager/logind-handle-lid-switch": false
    "/xfce4-power-manager/logind-handle-power-key": false
    "/xfce4-power-manager/logind-handle-suspend-key": false
  pointers:
    "/Razer_Razer_DeathAdder_Elite/Acceleration": 0.0
panels:
- size: 30
  length: 100
  length-adjust: false
  position: p=10;x=0;y=0
  position-locked: true
  icon-size: 16
  plugins:
  - - whiskermenu
  - - tasklist
    - grouping: 0
      sort-order: 0
      flat-buttons: true
  - - separator
    - expand: true
      style: 0
  - - windowmenu
  - - separator
    - style: 0
  - - pager
    - rows: 2
  - - separator
    - style: 0
  - - systray
    - icon-size: 16
      square-icons: true
  - - mailwatch
  - - pulseaudio
  - - power-manager-plugin
  - - notification-plugin
  - - clock
    - digital-format: "%R"
