Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/GlobalVars:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/AndOr:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
