#!/bin/bash

readarray -t files < <(git ls-files)

for f in "${files[@]}"; do
  [[ "$f" == tools/* ]] && continue
  if [[ -e ~/"$f" ]]
  then
    cmp -s {.,~}/"$f" || vimdiff {.,~}/"$f"
  else
    mkdir -p $(dirname ~/"$f") &&
    cp -av ./"$f" ~/"$f"
  fi
done

# extra

mkdir -p ~/.vim/autoload/ ~/.vim/bundle/
test -f ~/.vim/autoload/pathogen.vim || \
	curl -o ~/.vim/autoload/pathogen.vim 'https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim'

test -f ~/.git-prompt.sh || \
	curl -o ~/.git-prompt.sh 'http://git.kernel.org/?p=git/git.git;a=blob_plain;f=contrib/completion/git-prompt.sh'

chmod go-rw ~/.msmtprc

bundle config BUNDLE_PATH $(ruby -e 'puts Gem.user_dir')
