#!/bin/bash

cmp_all () {
  readarray -t files < <(git ls-files)

  for f in "${files[@]}"; do
    [[ "$f" == tools/* ]] && continue
    if [[ -e ~/"$f" ]]
    then
      cmp -s {.,~}/"$f" || vimdiff {.,~}/"$f"
    else
      mkdir -p $(dirname ~/"$f") &&
      cp -av ./"$f" ~/"$f"
    fi
  done
}

setup () {
  xdg-settings set default-web-browser chromium.desktop
  sudo chsh -s /bin/zsh felipec

  url='https://git.kernel.org/pub/scm/git/git.git/plain/contrib/completion'

  curl -o ~/.git-prompt.sh "${url}/git-prompt.sh"
  curl -o ~/.git-completion.bash "${url}/git-completion.bash"
  curl -o ~/.zsh/_git "${url}/git-completion.zsh"

  chmod go-rw ~/.msmtprc

  # XDG user dirs
  mkdir -p ~/{Desktop,Downloads,Templates,Public,Documents}
  mkdir -p ~/Documents/{Music,Pictures,Videos}

  mkdir -p ~/.local/share/histstat

  # vim zsh ruby git
  # xdg-user-dirs
  # chromium
  # ccache
  # conky
  # light

  git clone https://github.com/vim-airline/vim-airline ~/.vim/pack/dist/start/vim-airline
  git clone https://github.com/vim-syntastic/syntastic ~/.vim/pack/dist/start/syntastic
  git clone https://github.com/tpope/vim-commentary ~/.vim/pack/dist/start/vim-commentary
}

cmp_all
test -f ~/.config/dotfiles-setup || setup && touch ~/.config/dotfiles-setup
