#!/bin/sh

git ls-files | while read f; do
  [[ "$f" == tools/* ]] && continue
  if [[ -e ~/"$f" ]]
  then
    cmp -s {.,~}/"$f" || gvimdiff {.,~}/"$f"
  else
    mkdir -p $(dirname ~/"$f") &&
    cp -a ./"$f" ~/"$f"
  fi
done

# extra

test -f ~/.zprofile || ln -s .profile ~/.zprofile
