#!/usr/bin/env ruby

$versions = {}

Dir.chdir("/boot")
Dir.glob("*-*") do |fn|
  if (fn =~ /(config|System.map|vmlinuz)-(.*)/)
    $versions[$2] = true
  end
  if (fn =~ /System-(.*).map/)
    $versions[$1] = true
  end
  if (fn =~ /(initramfs)-(.*)\.img/)
    $versions[$2] = true
  end
end

Dir.chdir("/lib/modules")
Dir.glob("*") do |fn|
  $versions[fn] = true
end

current = `uname -r`.chomp
$versions.delete(current)
$versions.delete('linux')
$versions.delete('linux-fallback')

$versions.each_key do |v|
  next if v =~ /\.fc\d+\./ or v =~ /-ARCH$/ or v =~ /\.old$/
  print "#{v} [yN]: "
  next if not STDIN.gets =~ /^y/i
  system "rm -rfv /boot/{config,System.map,vmlinuz}-#{v} /boot/System-#{v}.map /boot/initramfs-#{v}.img /lib/modules/#{v}/"
end
