command_keyboard_shortcuts:
  "<Super>Return": xfce4-terminal
  "<Super>b": chromium
  "<Super>e": thunar
  "<Super>space": xfce4-terminal --drop-down --hide-menubar
  "<Super>l": light-locker-command --lock
  "<Super>w": xfce4-popup-whiskermenu
  "<Super>r": rlaunch
  "Print": xfce4-screenshooter

wm_keyboard_shortcuts:
  workspace_1: "<Super>1"
  workspace_2: "<Super>2"
  workspace_3: "<Super>3"
  workspace_4: "<Super>4"
  workspace_5: "<Super>5"
  workspace_6: "<Super>6"
  workspace_7: "<Super>7"
  workspace_8: "<Super>8"
  workspace_9: "<Super>9"
  workspace_10: "<Super>0"
  left_workspace: "<Super>Left"
  right_workspace: "<Super>Right"
  up_workspace: "<Super>Up"
  down_workspace: "<Super>Down"
  show_desktop: "<Super>d"
  move_window_left_workspace: "<Primary><Super>Left"
  move_window_right_workspace: "<Primary><Super>Right"
  move_window_up_workspace: "<Primary><Super>Up"
  move_window_down_workspace: "<Primary><Super>Down"
  move_window_workspace_1: "<Primary><Super>1"
  move_window_workspace_2: "<Primary><Super>2"
  move_window_workspace_3: "<Primary><Super>3"
  move_window_workspace_4: "<Primary><Super>4"
  move_window_workspace_5: "<Primary><Super>5"
  move_window_workspace_6: "<Primary><Super>6"
  move_window_workspace_7: "<Primary><Super>7"
  move_window_workspace_8: "<Primary><Super>8"
  move_window_workspace_9: "<Primary><Super>9"
  move_window_workspace_10: "<Primary><Super>0"

settings:
  xfwm4:
    "/general/workspace_count": 8
    "/general/easy_click": "Super"
    "/general/cycle_tabwin_mode": 1
    "/general/placement_ratio": 60
    "/general/title_font": "Sans Bold 10"
    "/general/cycle_raise": false
    "/general/cycle_hidden": false
    "/general/scroll_workspaces": false
    "/general/titleless_maximize": true
  keyboards:
    "/Default/KeyRepeat/Delay": 200
    "/Default/KeyRepeat/Rate": 50
  keyboard-layout:
    "/Default/XkbDisable": false
    "/Default/XkbLayout": "us"
    "/Default/XkbVariant": "altgr-intl"
  pointers:
    "/ELAN130100_04F33035_Touchpad/ReverseScrolling": true
    "/ELAN130100_04F33035_Touchpad/Properties/libinput_Tapping_Enabled": 1
  xfce4-desktop:
    "/desktop-icons/style": 0
  xfce4-session:
    "/general/SaveOnExit": false
    "/general/LockCommand": "light-locker-command --lock"
    "/compat/LaunchGNOME": true
  xfce4-power-manager:
    "/xfce4-power-manager/lid-action-on-ac": 1
    "/xfce4-power-manager/lid-action-on-battery": 1
    "/xfce4-power-manager/logind-handle-lid-switch": true
    "/xfce4-power-manager/sleep-button-action": 1
    "/xfce4-power-manager/power-button-action": 4
    "/xfce4-power-manager/general-notification": false
    "/xfce4-power-manager/inactivity-on-ac": 15
    "/xfce4-power-manager/inactivity-on-battery": 15
    "/xfce4-power-manager/show-panel-label": 1
  xfce4-notifyd:
    "/expire-timeout": 4
    "/primary-monitor": 1
    "/do-slideout": true
    "/notification-log": true
  xsettings:
    "/Gtk/FontName": "Sans 12"
    "/Gtk/MonospaceFontName": "Monospace 12"
    "/Net/CursorBlinkTime": 500
    "/Xft/DPI": 120
    "/Xft/HintStyle": "hintslight"
    "/Xft/RGBA": "rgb"
    "/Xft/Hinting": 1

panels:
- size: 30
  length: 100
  length-adjust: false
  position: "p=8;x=960;y=1064"
  position-locked: true
  icon-size: 16
  plugins:
  - - whiskermenu
  - - separator
    - style: 2
  - - windowmenu
    - style: 1
      all-workspaces: true
      workspace-names: true
      urgency-notification: false
  - - tasklist
    - flat-buttons: true
      grouping: 0
      show-labels: true
      show-handle: false
      sort-order: 0
      show-wireframes: false
      switch-workspace-on-unminimize: true
  - - separator
    - expand: true
      style: 0
  - - pager
    - rows: 2
      miniature-view: true
      workspace-scrolling: false
  - - statusnotifier
    - square-icons: true
      icon-size: 16
      symbolic-icons: true
  - - systray
    - square-icons: true
      size-max: 16
  - - power-manager-plugin
  - - notification-plugin
  - - pulseaudio
    - enable-keyboard-shortcuts: true
  - - clock
    - digital-format: "%R"
