#!/usr/bin/env ruby

require 'inifile'

config = ENV['XDG_CONFIG_HOME'] || "#{Dir.home}/.config"
$list_file = IniFile.load("#{config}/mimeapps.list")
$defaults = $list_file['Default Applications']
$ignore = %w[x-scheme-handler/http x-scheme-handler/https]

$dirs = ENV['XDG_DATA_DIRS']&.split(':') || '/usr/local/share/:/usr/share/'

apps = %w[nvim viewnior atril gimp mpv chromium]

apps = ARGV unless ARGV.empty?

$types = Hash.new { |h,k| h[k] = Array.new }

# clear values
# $defaults.each_key { |k| $defaults[k] = nil }

apps.each do |app|
  file = $dirs.map { "#{it}/applications/#{app}.desktop" }.find { File.exist?(it) }
  unless file
    STDERR.puts "#{app} not installed"
    next
  end

  File.open(file) do |f|
    f.each do |l|
      next unless l =~ /^MimeType=(.*)$/
      mimetypes = $1.split(';').each
      puts '%s: %d' % [app, mimetypes.count]
      mimetypes.each do |type|
        next if $ignore.include?(type)
        $types[type] << "#{app}.desktop"
      end
    end
  end
end

$types.sort.each do |type, apps|
  $defaults[type] = apps.join(';')
end

File.write($list_file.filename, $list_file.to_s.gsub(' = ', '='))
