#!/usr/bin/env ruby

require 'fileutils'

$versions = Dir.children('/lib/modules')

$versions.each do |v|
  next if v =~ /-(arch|zen)\d+-/
  print '%s [yN]: ' % v
  next unless STDIN.gets =~ /^y/i
  FileUtils.rm_rf('/lib/modules/' + v)
end
